kind: pipeline
type: exec
name: backend-builder

platform:
  os: linux
  arch: amd64

steps:
  - name: building-image
    commands:
      - docker build -t new_backend:latest .
  - name: running-image
    commands:
      - docker-compose -f /home/shared/conf_files/docker-compose.yml up -d

trigger:
  branch: 
    - master
  event:
    - tag